Bring repo to 2020
real-digital/pyconnect pull request #19
Opened 2020-10-22 20:48 UTC by hfjn

Ok this is a big one:
* Removed setup.py, setup.cfg and pipenv and merged everything into poetry
* I pretty much copied over the github actions and docker setup from esque
    * Unsure if the pipeline works. Might need your help here.
* Removed need for kafka binaries from test suite 
    * Tested locally & ran through
    * What could be done is executed by the confluent-admin-client, offsets are fetched with pykafka
    * Removed all subprocess calls for status checking -> Only ones left are in test_examples.py
* Disabled json logging in test suite so you can actually understand what's going on
* Added isort to pre-commit

I had a few other ideas but I thought I just push this upstream before I lose myself. 😄

2020-10-29 14:00 UTC, swenzel requested changes

2020-10-29 14:00 UTC, swenzel commented on test/docker-compose.yml
> -# Based on https://github.com/confluentinc/cp-docker-images/blob/master/examples/cp-all-in-one/docker-compose.yml
The Makefile still points to this file

2020-10-30 18:58 UTC, hfjn commented on .github/workflows/testing.yml
> +        if: matrix.python == '3.8' && steps.rdkafka-cache.outputs.cache-hit != 'true'
Aight. Bumped to 3.9.

2021-04-09 09:10 UTC, swenzel approved these changes
We'll fix the tests for the examples in another branch.

2021-04-09 09:10 UTC, merged